n = int(input())
L = map(int, input().split())
m = int(input())
V = map(int, input().split())
s1 = set(L)
s2 = set(V)
print(s1.difference(s2))
# print(len(s2.union(s1)))
print(len(s1.difference(s2)))
